package forecast

import (
	"math"
	"testing"
	"time"
)

// makeSeries creates a test series of n daily points starting from a base time,
// with values generated by the given function.
func makeSeries(n int, fn func(i int) float64) Series {
	base := time.Date(2026, 1, 1, 0, 0, 0, 0, time.UTC)
	s := make(Series, n)
	for i := 0; i < n; i++ {
		s[i] = Point{
			T: base.AddDate(0, 0, i),
			V: fn(i),
		}
	}
	return s
}

func TestRun_MinimumDataPoints(t *testing.T) {
	s := makeSeries(2, func(i int) float64 { return float64(i) })
	_, err := Run(s, Config{Method: MethodLinear, Horizon: 3})
	if err == nil {
		t.Fatal("expected error for < 3 data points")
	}
}

func TestRun_LinearTrend(t *testing.T) {
	// y = 10 + 5*x — clear upward trend.
	s := makeSeries(30, func(i int) float64 { return 10 + 5*float64(i) })

	result, err := Run(s, Config{
		Method:   MethodLinear,
		Horizon:  5,
		Interval: IntervalDay,
		Metric:   "total_income",
	})
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	if result.Method != MethodLinear {
		t.Errorf("method = %q, want %q", result.Method, MethodLinear)
	}
	if result.Metric != "total_income" {
		t.Errorf("metric = %q, want %q", result.Metric, "total_income")
	}
	if len(result.Predictions) != 5 {
		t.Fatalf("got %d predictions, want 5", len(result.Predictions))
	}
	if result.DataPoints != 30 {
		t.Errorf("data_points = %d, want 30", result.DataPoints)
	}

	// With a perfect linear series, the slope should be exactly 5.
	if math.Abs(result.Trend-5.0) > 0.01 {
		t.Errorf("trend = %.4f, want ~5.0", result.Trend)
	}

	// First prediction should be ~10 + 5*30 = 160.
	expected := 10 + 5.0*30
	if math.Abs(result.Predictions[0].Value-expected) > 0.1 {
		t.Errorf("first prediction = %.2f, want ~%.2f", result.Predictions[0].Value, expected)
	}

	// Bounds should be present and ordered.
	for i, p := range result.Predictions {
		if p.LowerBound > p.Value {
			t.Errorf("prediction[%d]: lower_bound (%.2f) > value (%.2f)", i, p.LowerBound, p.Value)
		}
		if p.UpperBound < p.Value {
			t.Errorf("prediction[%d]: upper_bound (%.2f) < value (%.2f)", i, p.UpperBound, p.Value)
		}
	}
}

func TestRun_LinearFlat(t *testing.T) {
	// Flat series — should predict the same constant value.
	s := makeSeries(20, func(i int) float64 { return 42.0 })

	result, err := Run(s, Config{Method: MethodLinear, Horizon: 3})
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	for _, p := range result.Predictions {
		if math.Abs(p.Value-42.0) > 0.01 {
			t.Errorf("flat prediction = %.4f, want 42.0", p.Value)
		}
	}
	if math.Abs(result.Trend) > 0.01 {
		t.Errorf("trend = %.4f, want ~0", result.Trend)
	}
}

func TestRun_SMA(t *testing.T) {
	// Last 5 values average to (10+11+12+13+14)/5 = 12.
	s := makeSeries(15, func(i int) float64 { return float64(i) })

	result, err := Run(s, Config{
		Method:    MethodSMA,
		Horizon:   3,
		Interval:  IntervalDay,
		SMAWindow: 5,
	})
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	if result.Method != MethodSMA {
		t.Errorf("method = %q, want %q", result.Method, MethodSMA)
	}

	// SMA of last 5 points: (10+11+12+13+14)/5 = 12.
	expectedAvg := 12.0
	for _, p := range result.Predictions {
		if math.Abs(p.Value-expectedAvg) > 0.01 {
			t.Errorf("SMA prediction = %.4f, want ~%.1f", p.Value, expectedAvg)
		}
	}
}

func TestRun_WMA(t *testing.T) {
	// WMA with window=3 on [10, 20, 30]:
	// (10*1 + 20*2 + 30*3) / (1+2+3) = (10+40+90)/6 = 140/6 ≈ 23.33.
	s := makeSeries(3, func(i int) float64 { return float64((i + 1) * 10) })

	result, err := Run(s, Config{
		Method:    MethodWMA,
		Horizon:   2,
		Interval:  IntervalDay,
		SMAWindow: 3,
	})
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	expected := 140.0 / 6.0
	for _, p := range result.Predictions {
		if math.Abs(p.Value-expected) > 0.1 {
			t.Errorf("WMA prediction = %.4f, want ~%.2f", p.Value, expected)
		}
	}
}

func TestRun_HoltWinters(t *testing.T) {
	// Linear trend with noise — Holt-Winters should capture the upward trend.
	s := makeSeries(30, func(i int) float64 {
		// Base trend + small oscillation.
		return 100 + 3*float64(i) + 2*math.Sin(float64(i)*0.5)
	})

	result, err := Run(s, Config{
		Method:   MethodHoltWinters,
		Horizon:  5,
		Interval: IntervalDay,
	})
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	if result.Method != MethodHoltWinters {
		t.Errorf("method = %q, want %q", result.Method, MethodHoltWinters)
	}

	// Predictions should be in the 190+ range (100 + 3*30 = 190 baseline).
	for _, p := range result.Predictions {
		if p.Value < 150 || p.Value > 250 {
			t.Errorf("HoltWinters prediction %.2f out of expected range [150, 250]", p.Value)
		}
	}

	// Trend should be positive (roughly 3).
	if result.Trend <= 0 {
		t.Errorf("expected positive trend, got %.4f", result.Trend)
	}
}

func TestRun_Auto(t *testing.T) {
	s := makeSeries(30, func(i int) float64 { return 50 + 2*float64(i) })

	result, err := Run(s, Config{
		Method:   MethodAuto,
		Horizon:  5,
		Interval: IntervalDay,
	})
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	// Auto should pick a method and produce valid predictions.
	if result.Method == MethodAuto {
		t.Error("auto should resolve to a concrete method")
	}
	if len(result.Predictions) != 5 {
		t.Errorf("got %d predictions, want 5", len(result.Predictions))
	}
}

func TestRun_BoundsWiden(t *testing.T) {
	// Bounds should widen as we forecast further out.
	s := makeSeries(30, func(i int) float64 { return 100 + float64(i) + 5*math.Sin(float64(i)) })

	result, err := Run(s, Config{
		Method:   MethodLinear,
		Horizon:  10,
		Interval: IntervalDay,
	})
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	firstSpread := result.Predictions[0].UpperBound - result.Predictions[0].LowerBound
	lastSpread := result.Predictions[9].UpperBound - result.Predictions[9].LowerBound

	if lastSpread <= firstSpread {
		t.Errorf("bounds should widen: first spread=%.2f, last spread=%.2f", firstSpread, lastSpread)
	}
}

func TestRun_TimeProgression(t *testing.T) {
	s := makeSeries(10, func(i int) float64 { return float64(i) })

	result, err := Run(s, Config{
		Method:   MethodLinear,
		Horizon:  3,
		Interval: IntervalDay,
	})
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	lastData := s[len(s)-1].T
	for i, p := range result.Predictions {
		expected := lastData.AddDate(0, 0, i+1)
		if !p.T.Equal(expected) {
			t.Errorf("prediction[%d] time = %v, want %v", i, p.T, expected)
		}
	}
}

func TestRun_WeekInterval(t *testing.T) {
	base := time.Date(2026, 1, 5, 0, 0, 0, 0, time.UTC) // Monday
	s := make(Series, 10)
	for i := 0; i < 10; i++ {
		s[i] = Point{T: base.AddDate(0, 0, i*7), V: float64(i * 100)}
	}

	result, err := Run(s, Config{
		Method:   MethodLinear,
		Horizon:  3,
		Interval: IntervalWeek,
	})
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	lastData := s[len(s)-1].T
	for i, p := range result.Predictions {
		expected := lastData.AddDate(0, 0, (i+1)*7)
		if !p.T.Equal(expected) {
			t.Errorf("prediction[%d] time = %v, want %v", i, p.T, expected)
		}
	}
}

func TestRun_MonthInterval(t *testing.T) {
	base := time.Date(2026, 1, 1, 0, 0, 0, 0, time.UTC)
	s := make(Series, 6)
	for i := 0; i < 6; i++ {
		s[i] = Point{T: base.AddDate(0, i, 0), V: float64(1000 + i*50)}
	}

	result, err := Run(s, Config{
		Method:   MethodLinear,
		Horizon:  3,
		Interval: IntervalMonth,
	})
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	lastData := s[len(s)-1].T
	for i, p := range result.Predictions {
		expected := lastData.AddDate(0, i+1, 0)
		if !p.T.Equal(expected) {
			t.Errorf("prediction[%d] time = %v, want %v", i, p.T, expected)
		}
	}
}

func TestRun_TrendPercentage(t *testing.T) {
	// y = 100 + 10*x, mean ≈ 245, slope = 10, trend_pct ≈ 10/245 * 100 ≈ 4.08%.
	s := makeSeries(30, func(i int) float64 { return 100 + 10*float64(i) })

	result, err := Run(s, Config{Method: MethodLinear, Horizon: 1})
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	if result.TrendPct <= 0 {
		t.Errorf("expected positive trend_pct, got %.4f", result.TrendPct)
	}
}

func TestRun_SeasonalWeights(t *testing.T) {
	s := makeSeries(14, func(i int) float64 { return 100 })

	weights := SeasonalWeights{
		time.Monday:  1.5,
		time.Tuesday: 0.8,
	}

	result, err := Run(s, Config{
		Method:          MethodSMA,
		Horizon:         7,
		Interval:        IntervalDay,
		SeasonalWeights: weights,
	})
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	// Find which predictions fall on Monday/Tuesday and verify they were adjusted.
	for _, p := range result.Predictions {
		dow := p.T.Weekday()
		if dow == time.Monday && math.Abs(p.Value-150) > 5 {
			t.Errorf("Monday prediction = %.2f, expected ~150 (100 * 1.5)", p.Value)
		}
		if dow == time.Tuesday && math.Abs(p.Value-80) > 5 {
			t.Errorf("Tuesday prediction = %.2f, expected ~80 (100 * 0.8)", p.Value)
		}
	}
}

func TestRun_DefaultConfig(t *testing.T) {
	s := makeSeries(30, func(i int) float64 { return float64(i * 10) })

	result, err := Run(s, Config{})
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	// Defaults: horizon=7, interval=day, method=auto, confidence=0.95.
	if result.Horizon != 7 {
		t.Errorf("default horizon = %d, want 7", result.Horizon)
	}
	if result.Interval != IntervalDay {
		t.Errorf("default interval = %q, want %q", result.Interval, IntervalDay)
	}
	if len(result.Predictions) != 7 {
		t.Errorf("got %d predictions, want 7", len(result.Predictions))
	}
}

func TestBacktest_ProducesMetrics(t *testing.T) {
	s := makeSeries(30, func(i int) float64 { return 50 + 2*float64(i) + 3*math.Sin(float64(i)) })

	result, err := Run(s, Config{Method: MethodLinear, Horizon: 5})
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	if result.MAE < 0 {
		t.Errorf("MAE should be non-negative, got %.4f", result.MAE)
	}
	if result.RMSE < 0 {
		t.Errorf("RMSE should be non-negative, got %.4f", result.RMSE)
	}
	if result.RMSE < result.MAE {
		t.Errorf("RMSE (%.4f) should be >= MAE (%.4f)", result.RMSE, result.MAE)
	}
}

func TestSeriesMean(t *testing.T) {
	s := Series{{V: 10}, {V: 20}, {V: 30}}
	got := seriesMean(s)
	if math.Abs(got-20.0) > 0.001 {
		t.Errorf("seriesMean = %.2f, want 20.0", got)
	}
}

func TestSeriesStdDev(t *testing.T) {
	s := Series{{V: 10}, {V: 20}, {V: 30}}
	got := seriesStdDev(s)
	// Population stddev of [10,20,30] = sqrt(200/3) ≈ 8.165.
	expected := math.Sqrt(200.0 / 3.0)
	if math.Abs(got-expected) > 0.01 {
		t.Errorf("seriesStdDev = %.4f, want ~%.4f", got, expected)
	}
}

func TestZScore(t *testing.T) {
	tests := []struct {
		conf     float64
		expected float64
	}{
		{0.99, 2.576},
		{0.95, 1.960},
		{0.90, 1.645},
		{0.80, 1.282},
		{0.50, 1.960}, // fallback
	}
	for _, tc := range tests {
		got := zScore(tc.conf)
		if got != tc.expected {
			t.Errorf("zScore(%.2f) = %.3f, want %.3f", tc.conf, got, tc.expected)
		}
	}
}

func TestValidMethods(t *testing.T) {
	methods := ValidMethods()
	if len(methods) != 5 {
		t.Errorf("expected 5 valid methods, got %d", len(methods))
	}
}

func TestValidIntervals(t *testing.T) {
	intervals := ValidIntervals()
	if len(intervals) != 4 {
		t.Errorf("expected 4 valid intervals, got %d", len(intervals))
	}
}
