<?php

declare(strict_types=1);

namespace Tests\DataEngine;

use PHPUnit\Framework\TestCase;

/**
 * Tests for the slim DataEngine used on the tracking hot path.
 *
 * The rollup INSERT ... SELECT statement itself is generated by
 * Prosper202\DataEngine\ClickRollupSql and covered by ClickRollupSqlTest;
 * these tests verify the slim engine's own wiring (the source cannot be
 * instantiated without the DB singleton and global state).
 */
final class DataEngineTest extends TestCase
{
    private string $source;

    protected function setUp(): void
    {
        $source = file_get_contents(__DIR__ . '/../../202-config/class-dataengine-slim.php');
        self::assertNotFalse($source, 'class-dataengine-slim.php must be readable');
        $this->source = $source;
    }

    public function testSlimEngineUsesTheSharedRollupBuilder(): void
    {
        self::assertStringContainsString(
            'ClickRollupSql::insertSelect',
            $this->source,
            'The slim engine must not carry its own copy of the rollup SQL'
        );
    }

    public function testEmptyClickIdReturnsEarly(): void
    {
        self::assertStringContainsString(
            'return false',
            $this->source,
            'Empty click_id must cause early return'
        );
    }

    /**
     * It did, to the user's offset today rounded to whole hours, and for the
     * rest of the request; east of UTC without the sign, which MySQL
     * refuses. The rollup reads no clock, and the reports read the
     * account's with LocalTime (tests/DataEngine/TimeGroupingIntegrationTest).
     */
    public function testSlimEngineLeavesTheConnectionsZoneAlone(): void
    {
        self::assertDoesNotMatchRegularExpression(
            '/\btime_zone\b/i',
            $this->source,
            'The slim engine must not set the connection\'s time zone'
        );
    }

    /**
     * A request that names no click re-rolls none, in either engine. Both
     * took "the visitor's latest click" instead: user 1's newest click from
     * the address in $ip_address in the last 24 hours, so a cookie-less
     * lpc.php request re-rolled user 1's click from that address — a lookup
     * and a rollup for a request that changed no click, reading only user
     * 1's clicks and the global address rather than the stored one.
     */
    public function testNeitherEngineLooksAClickUpByAddress(): void
    {
        $full = (string) file_get_contents(__DIR__ . '/../../202-config/class-dataengine.php');
        foreach (['slim' => $this->source, 'full' => $full] as $engine => $source) {
            $body = self::methodBody($source, 'setDirtyHour');
            $read = "$engine: the body read is setDirtyHour()'s";
            self::assertStringContainsString('ClickRollupSql::insertSelect', $body, $read);
            foreach (['$ip_address', '202_ips', 'user_id'] as $read) {
                self::assertStringNotContainsString($read, $body, "$engine: setDirtyHour() reads $read");
            }
        }
    }

    /** A function's body, from its opening brace to the brace that closes it, read from tokens. */
    private static function methodBody(string $source, string $name): string
    {
        $tokens = token_get_all($source);
        foreach ($tokens as $i => $token) {
            if (!is_array($token) || $token[0] !== T_FUNCTION) {
                continue;
            }
            $j = $i + 1;
            while (is_array($tokens[$j]) && $tokens[$j][0] === T_WHITESPACE) {
                $j++;
            }
            if (!is_array($tokens[$j]) || $tokens[$j][1] !== $name) {
                continue;
            }
            while ($tokens[$j] !== '{') {
                $j++;
            }
            $depth = 0;
            $body = '';
            for ($k = $j; $k < count($tokens); $k++) {
                $text = is_array($tokens[$k]) ? $tokens[$k][1] : $tokens[$k];
                $opens = is_array($tokens[$k])
                    && in_array($tokens[$k][0], [T_CURLY_OPEN, T_DOLLAR_OPEN_CURLY_BRACES], true);
                if ($text === '{' || $opens) {
                    $depth++;
                } elseif ($text === '}') {
                    $depth--;
                }
                $body .= $text;
                if ($depth === 0) {
                    return $body;
                }
            }
        }
        self::fail("no function $name()");
    }

    public function testSlimEngineIsGuardedAgainstRedeclaration(): void
    {
        self::assertStringContainsString(
            "class_exists('DataEngine')",
            $this->source,
            'The slim engine must not collide with the full engine when both are included'
        );
    }
}
