<?php

declare(strict_types=1);

namespace Tests\DataEngine;

use PHPUnit\Framework\TestCase;

/**
 * Tests for the slim DataEngine used on the tracking hot path.
 *
 * The rollup INSERT ... SELECT statement itself is generated by
 * Prosper202\DataEngine\ClickRollupSql and covered by ClickRollupSqlTest;
 * these tests verify the slim engine's own wiring (the source cannot be
 * instantiated without the DB singleton and global state).
 */
final class DataEngineTest extends TestCase
{
    private string $source;

    protected function setUp(): void
    {
        $source = file_get_contents(__DIR__ . '/../../202-config/class-dataengine-slim.php');
        self::assertNotFalse($source, 'class-dataengine-slim.php must be readable');
        $this->source = $source;
    }

    public function testSlimEngineUsesTheSharedRollupBuilder(): void
    {
        self::assertStringContainsString(
            'ClickRollupSql::insertSelect',
            $this->source,
            'The slim engine must not carry its own copy of the rollup SQL'
        );
    }

    public function testSlimEngineRefreshesLandingPageOnDuplicate(): void
    {
        self::assertStringContainsString(
            'updateLandingPageId: true',
            $this->source,
            'Postbacks must refresh landing_page_id when the click already exists'
        );
    }

    public function testEmptyClickIdReturnsEarly(): void
    {
        self::assertStringContainsString(
            'return false',
            $this->source,
            'Empty click_id must cause early return'
        );
    }

    public function testDataEngineSetsMysqlTimezone(): void
    {
        self::assertStringContainsString(
            'SET time_zone',
            $this->source,
            'DataEngine must set MySQL timezone for correct time-based aggregation'
        );
    }

    public function testClickIdFromIpLookupIsEscaped(): void
    {
        self::assertStringContainsString(
            'real_escape_string',
            $this->source,
            'Click ID resolved from the DB lookup must be escaped before interpolation'
        );
    }

    public function testSlimEngineIsGuardedAgainstRedeclaration(): void
    {
        self::assertStringContainsString(
            "class_exists('DataEngine')",
            $this->source,
            'The slim engine must not collide with the full engine when both are included'
        );
    }
}
