<?php

declare(strict_types=1);

namespace Tests\Goals;

use PHPUnit\Framework\TestCase;
use Prosper202\Goals\EvaluationState;
use Prosper202\Goals\GoalDefinition;
use Prosper202\Goals\GoalEvaluator;
use Prosper202\Goals\GoalEvent;
use Prosper202\Goals\GoalSpec;
use Prosper202\Goals\GoalSubject;
use Prosper202\Goals\InvalidGoalDefinition;

/**
 * The PHP evaluator against the cross-language vectors in
 * tests/fixtures/app-sdk-contract/goals/ — the same files the Swift (PR 8)
 * and Kotlin (PR 7) evaluators are to be tested against, so the three cannot
 * drift. Every expectation there was written by hand from the README's
 * rules, not generated by running this code.
 *
 * Two runs per case: the whole evaluation from nothing (evaluateAll), and
 * the incremental one the server uses for an in-order event — one event at
 * a time, continuing from the state the last left (continueFrom). They must
 * agree on every case, which is the proof that the engine's two paths
 * (incremental and replay) cannot fork.
 */
final class GoalVectorsTest extends TestCase
{
    private const DIR = __DIR__ . '/../fixtures/app-sdk-contract/goals';

    /** @return array<string, mixed> */
    private static function load(string $file): array
    {
        $raw = file_get_contents(self::DIR . '/' . $file);
        self::assertIsString($raw, $file . ' is missing');
        $decoded = json_decode($raw, true, 64, JSON_THROW_ON_ERROR);
        self::assertIsArray($decoded);
        self::assertSame(1, $decoded['format_version'] ?? null, $file . ': this suite reads format_version 1');

        return $decoded;
    }

    /** @return array<string, array{0: array<string, mixed>}> */
    public static function evaluatorCases(): array
    {
        $out = [];
        foreach (self::load('evaluator.json')['cases'] as $case) {
            $out[$case['name']] = [$case];
        }

        return $out;
    }

    /** @return array<string, array{0: array<string, mixed>}> */
    public static function definitionCases(): array
    {
        $out = [];
        foreach (self::load('definitions.json')['cases'] as $case) {
            $out[$case['name']] = [$case];
        }

        return $out;
    }

    public function testTheVectorFilesHoldEnoughCasesToMeanSomething(): void
    {
        // Guards the provider: a file that decoded to no cases would pass
        // every data-provided test by running none of them.
        self::assertGreaterThanOrEqual(40, count(self::evaluatorCases()));
        self::assertGreaterThanOrEqual(40, count(self::definitionCases()));
    }

    /**
     * @dataProvider evaluatorCases
     * @param array<string, mixed> $case
     */
    public function testEvaluatorVector(array $case): void
    {
        [$specs, $subject, $events] = self::inputs($case);

        $result = GoalEvaluator::evaluateAll($specs, $subject, $events)->toArray();
        self::assertSame($case['expect']['outcomes'], $result['outcomes'], 'outcomes');
        self::assertSame($case['expect']['disabled'], $result['disabled'], 'disabled');
        if (isset($case['expect']['progress'])) {
            self::assertSame($case['expect']['progress'], $result['progress'], 'progress');
        }
    }

    /**
     * @dataProvider evaluatorCases
     * @param array<string, mixed> $case
     */
    public function testOneEventAtATimeFromTheStoredStateAgrees(array $case): void
    {
        [$specs, $subject, $events] = self::inputs($case);
        if ($subject->type === GoalSubject::INSTALL && $subject->installAt !== null) {
            $events[] = GoalEvent::install($subject->installAt);
        }
        usort($events, [GoalEvent::class, 'compare']);

        $state = new EvaluationState();
        $outcomes = [];
        $disabled = [];
        foreach ($events as $event) {
            $step = GoalEvaluator::continueFrom($specs, $subject, $state, [$event]);
            foreach ($step->outcomes as $o) {
                $outcomes[] = $o->toArray();
            }
            foreach ($step->disabled as $d) {
                $disabled[$d['goal_id'] . ':' . $d['version'] . ':' . $d['reason']] = $d;
            }
            // What the engine does between requests: store the progress
            // and read it back.
            $state = self::roundTrip($step->state);
        }
        ksort($disabled);

        self::assertSame($case['expect']['outcomes'], $outcomes, 'incremental outcomes');
        if ($events !== []) {
            self::assertSame(
                array_map(static fn (array $d): string => $d['goal_id'] . ':' . $d['version'] . ':' . $d['reason'], $case['expect']['disabled']),
                array_keys($disabled),
                'incremental disabled'
            );
        }
    }

    /**
     * @dataProvider definitionCases
     * @param array<string, mixed> $case
     */
    public function testDefinitionVector(array $case): void
    {
        if ($case['valid']) {
            $definition = GoalDefinition::parse($case['definition']);
            self::assertSame($case['canonical'], $definition->toArray());
            // The canonical form is a fixed point: it parses to itself.
            self::assertSame($case['canonical'], GoalDefinition::fromJson($definition->toJson())->toArray());
            return;
        }
        try {
            GoalDefinition::parse($case['definition']);
            self::fail('accepted an invalid definition: ' . $case['name']);
        } catch (InvalidGoalDefinition $e) {
            $paths = array_keys($e->errors());
            sort($paths);
            $expected = $case['errors'];
            sort($expected);
            self::assertSame($expected, $paths);
        }
    }

    /**
     * @param array<string, mixed> $case
     * @return array{0: list<GoalSpec>, 1: GoalSubject, 2: list<GoalEvent>}
     */
    private static function inputs(array $case): array
    {
        $specs = [];
        foreach ($case['goals'] as $g) {
            $specs[] = new GoalSpec((int) $g['goal_id'], $g['versions'], (int) ($g['starts_at'] ?? 0), isset($g['ends_at']) ? (int) $g['ends_at'] : null);
        }
        $rebases = [];
        foreach ($case['subject']['rebases'] ?? [] as $goalId => $version) {
            $rebases[(int) $goalId] = (int) $version;
        }
        $subject = new GoalSubject(
            (string) $case['subject']['type'],
            1,
            $case['subject']['click_at'] ?? null,
            $case['subject']['install_at'] ?? null,
            $rebases,
        );
        $events = [];
        foreach ($case['events'] as $i => $e) {
            // Every vector event must be one the intake would accept.
            $events[] = GoalEvent::fromArray($e, 'events[' . $i . ']');
        }

        return [$specs, $subject, $events];
    }

    /** The state as 202_goal_progress stores it, read back. */
    private static function roundTrip(EvaluationState $state): EvaluationState
    {
        $copy = new EvaluationState();
        foreach ($state->progress as $key => $p) {
            $copy->progress[$key] = [
                'goal_id' => (int) (string) $p['goal_id'],
                'version' => (int) (string) $p['version'],
                'count' => (int) (string) $p['count'],
                'sum' => \Prosper202\Conversion\Ledger\Amount::toUnits(\Prosper202\Conversion\Ledger\Amount::fromUnits($p['sum'])),
                'times' => (int) (string) $p['times'],
                'reached_at' => $p['reached_at'],
            ];
        }
        $copy->reached = $state->reached;

        return $copy;
    }
}
